src/objects/Outage_Alert__c.object
<CustomObject>
    <fields>
        <fullName>Begin_Date_Time__c</fullName>
        <label>Begin Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <label>End Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Outage_SMS_Message_del__c</fullName>
        <label>Outage SMS Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Outage_Text__c</fullName>
        <label>Outage Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Outage_Type__c</fullName>
        <label>Outage Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Repair</fullName>
                </value>
                <value>
                    <fullName>Unplanned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stop__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Stop</label>
        <referenceTo>Stop__c</referenceTo>
        <relationshipLabel>Outage Alerts</relationshipLabel>
        <relationshipName>Outage_Alerts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Outage Alert</label>
    <nameField>
        <displayFormat>OA-{000000000}</displayFormat>
        <label>Outage Alert Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outage Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Outage_Template__c.object
<CustomObject>
    <fields>
        <fullName>Email_Body_Template__c</fullName>
        <label>Email Body Template</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SMS_Template__c</fullName>
        <label>SMS Template</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Outage Template</label>
    <nameField>
        <label>Outage Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outage Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Stop__c.object
<CustomObject>
    <fields>
        <fullName>Location_Type__c</fullName>
        <label>Location Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stop_Name__c</fullName>
        <label>Stop Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Stop</label>
    <nameField>
        <label>Stop ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OutageNotificationController.cls
global class OutageNotificationController {
	public OutageNotificationController() {
		
	}

	@AuraEnabled
    public static Outage_Alert__c getOutage(String id) {
        System.debug('getOutage invoked...');

        Outage_Alert__c o = [SELECT Id, Begin_Date_Time__c, End_Date_Time__c, Stop__c, Outage_Type__c, Outage_Text__c, Outage_SMS_Message_del__c FROM Outage_Alert__c WHERE Id = :id];
        return o;
    }

    @AuraEnabled
    public static Stop__c getStop(String id) {
        System.debug('getStop invoked...');

        Stop__c s = [SELECT Id, Name, Stop_Name__c, Location_Type__c FROM Stop__c WHERE Id = :id];
        return s;
    }

    @AuraEnabled
    public static Outage_Template__c getOutageTemplate(String id) {
        System.debug('getOutageTemplate invoked...');

        Outage_Template__c ot = [SELECT Id, Name, Email_Body_Template__c, SMS_Template__c FROM Outage_Template__c WHERE Id = :id];
        return ot;
    }

    @AuraEnabled
    public static List<Outage_Template__c> getOutageTemplates() {
        System.debug('getOutageTemplates invoked...');

        List<Outage_Template__c> otList = [SELECT Id, Name, Email_Body_Template__c, SMS_Template__c FROM Outage_Template__c];
        return otList;
    }

    @AuraEnabled
    public static List<Stop__c> getStops() {
        System.debug('getStops invoked...');

        List<Stop__c> stopList = [SELECT Id, Name, Stop_Name__c FROM Stop__c];
        return stopList;
    }

    @AuraEnabled
    public static void saveOutage(Outage_Alert__c outage) {
        System.debug('saveOutage invoked...');
        System.debug('outage: ' + outage);

        update outage;
    }
}